-- The check-in kiosk, and what a card reader can emit.
--
-- A SHARED TABLET IN A HALLWAY WITH CHILDREN AROUND IT. Everything here follows
-- from that one fact.
--
-- It must never hold a staff session. A borrowed or stolen tablet carrying one
-- would open every child's address, every guardian's phone number and every
-- allergy note. So the kiosk is a SEPARATE PRINCIPAL with exactly one
-- capability — check a child in — and it is deliberately not a `staff` row with
-- a narrow role, because SessionUser flows into every route in this app and one
-- missed check would hand a hallway tablet everything.
CREATE TABLE `kiosk_devices` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	-- What it is called on the register screen. "Foyer iPad".
	`name` text NOT NULL,
	-- The pairing secret, held in a cookie on that one tablet. Long, random and
	-- opaque, like a session token — and revocable the same way, because the
	-- realistic failure here is the tablet walking off, not the token leaking.
	`token` text NOT NULL,
	`active` integer DEFAULT 1 NOT NULL,
	-- So a director can tell a tablet that is working from one that has been
	-- unplugged since March. Written on each scan, not each request.
	`last_seen_at` text,
	`revoked_at` text,
	`created_by` text,
	`created_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `kiosk_devices_token` ON `kiosk_devices` (`token`);
--> statement-breakpoint

-- What a card reader actually hands over.
--
-- There are two kinds of thing a reader can emit and they are NOT
-- interchangeable:
--
--   the NDEF record — the URL we wrote to the tag, carrying our own opaque
--                     token. Secret, generated by us, revocable.
--   the tag's UID   — a serial number burned in by the chip manufacturer.
--                     NOT secret: it is fixed, often printed on the card, and
--                     trivially cloned onto a blank tag.
--
-- Most inexpensive readers emit the UID by default, so it has to be supported.
-- But it is stored SEPARATELY from the token, and the difference is the whole
-- point: a UID may check a child in and nothing more, while the token is what
-- opens that child's profile on a teacher's phone. Cloning a UID gets you the
-- ability to mark a child present, which is a nuisance. If the UID were the
-- profile key it would get you their address.
ALTER TABLE `kid_cards` ADD `uid` text;
--> statement-breakpoint
-- Unique where present, so one tag cannot be registered to two children — that
-- would make a scan ambiguous and credit the wrong child. Partial, because
-- most cards will have no UID until they are scanned once to learn it.
CREATE UNIQUE INDEX `kid_cards_uid` ON `kid_cards` (`uid`) WHERE `uid` IS NOT NULL;
