-- Which part of the app sent a message.
--
-- There is ONE Twilio number and there will not be a second (the pastor,
-- 2026-09-08): the A2P campaign already covers "updating constituents' families
-- on church events", which is exactly this scope, and a second line is a
-- recurring cost for nothing.
--
-- That decision is right, but it leaves the children's replies tab with a
-- problem. With one number, an inbound text carries no signal about which part
-- of the church it is answering — so that tab identified [Kids Ministry] conversations by
-- INFERRING them from the sender being a known guardian.
--
-- Most church parents ARE guardians. So a member texting the church about
-- anything at all — a prayer request, a bereavement — appeared in the children's
-- replies tab, readable by every [Kids Ministry] volunteer. Not what anybody intended,
-- and precisely the kind of leak this app is otherwise careful about.
--
-- So outbound messages record where they came from, and a conversation counts as
-- [Kids Ministry] only if we started it there. A guardian whose number is not ALSO a
-- member's stays unambiguous and needs no marker — a bus family has no other
-- reason to be texting.
ALTER TABLE `message_log` ADD `context` text;
--> statement-breakpoint
CREATE INDEX `message_log_context_idx` ON `message_log` (`context`);
